/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DyakuiemoRouteImport } from './routes/dyakuiemo'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ApiLeadRouteImport } from './routes/api/lead'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DyakuiemoRoute = DyakuiemoRouteImport.update({
  id: '/dyakuiemo',
  path: '/dyakuiemo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dyakuiemo': typeof DyakuiemoRoute
  '/privacy': typeof PrivacyRoute
  '/api/lead': typeof ApiLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dyakuiemo': typeof DyakuiemoRoute
  '/privacy': typeof PrivacyRoute
  '/api/lead': typeof ApiLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dyakuiemo': typeof DyakuiemoRoute
  '/privacy': typeof PrivacyRoute
  '/api/lead': typeof ApiLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dyakuiemo' | '/privacy' | '/api/lead'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dyakuiemo' | '/privacy' | '/api/lead'
  id: '__root__' | '/' | '/dyakuiemo' | '/privacy' | '/api/lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DyakuiemoRoute: typeof DyakuiemoRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiLeadRoute: typeof ApiLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dyakuiemo': {
      id: '/dyakuiemo'
      path: '/dyakuiemo'
      fullPath: '/dyakuiemo'
      preLoaderRoute: typeof DyakuiemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DyakuiemoRoute: DyakuiemoRoute,
  PrivacyRoute: PrivacyRoute,
  ApiLeadRoute: ApiLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
